[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.24.2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.1" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.7.0" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.1.0" }

[bundles]
unit-testing = ["assertj-core", "junit-jupiter", "mockito-core", "mockito-kotlin"]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.20" }
